#!/usr/bin/env node

"use strict";

require("events").EventEmitter.prototype._maxListeners = 100;

const fs    = require("fs");
const yaml  = require("js-yaml");
const {Dvr} = require("./lib/core/dvr");

function sleep(time) {
    return new Promise((resolve) => setTimeout(resolve, time));
}

class Streamdvr extends Dvr {

    constructor() {
        super(__dirname);
        this.plugins = [];

        // Scan the config.yml directory for plugins to load
        const allfiles = fs.readdirSync(this.configdir);
        const ymlfiles = allfiles.filter((x) => x.match(/.*\.yml$/ig) && !x.match(/.*_updates\.yml/ig) && x !== "config.yml");

        for (let i = 0; i < ymlfiles.length; i++) {
            console.log(this.configdir + ymlfiles[i]);
            const config = yaml.safeLoad(fs.readFileSync(this.configdir + ymlfiles[i], "utf8"));
            if (config && config.plugin && config.enable) {
                // TODO: print better error message if config.plugin doesn't exist
                this.plugins.push({
                    code:    require(config.plugin),
                    name:    config.name,
                    file:    config.plugin,
                    urlback: config.urlback,
                    enable:  config.enable,
                    handle:  null
                });
            }
        }

        for (const plugin of this.plugins.values()) {
            plugin.handle = new plugin.code.Plugin(plugin.name, this, this.tui, plugin.urlback);
        }

        process.on("SIGINT", () => {
            this.exit();
        });
    }

    async start() {
        for (const plugin of this.plugins.values()) {
            if (plugin.enable) {
                await plugin.handle.connect();
                this.run(plugin.handle);
            }
        }
    }

    busy() {
        for (const plugin of this.plugins.values()) {
            if (plugin.enable) {
                if (plugin.handle.getNumCapsInProgress() > 0) {
                    return true;
                }
            }
        }
        return false;
    }

    async tryExit() {
        while (true) {
            // delay exiting until all capture and postprocess
            // ffmpeg jobs have completed.
            if (!this.busy()) {
                for (const plugin of this.plugins.values()) {
                    if (plugin.enable) {
                        await plugin.handle.disconnect();
                    }
                }
                process.exit(0);
            } else {
                await sleep(1000);
            }
        }
    }

    exit() {
        // Prevent bad things from happening if user holds down ctrl+c
        if (!this.tryingToExit) {
            this.tryingToExit = true;
            if (this.busy()) {
                this.msg("Stopping all recordings...");
            }
            this.tryExit();
        }

        // Allow this to execute multiple times so that SIGINT
        // can get passed again to ffmpeg/streamlink in case some get hung.
        for (const plugin of this.plugins.values()) {
            if (plugin.enable) {
                plugin.handle.haltAllCaptures();
            }
        }
    }

}

const dvr = new Streamdvr();
dvr.start();
