name: MIXER
plugin: ./plugins/basic
siteUrl: https://mixer.com/
urlback: ""
enable: false
m3u8fetch: scripts/m3u8_youtubedl.sh
recorder: scripts/record_ffmpeg.sh
scanInterval: 300
batchSize: 5
streamers:
