name: PICARTO
plugin: ./lib/plugins/basic
siteUrl: https://picarto.tv/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_streamlink.sh
m3u8fetch_args: []
recorder: scripts/record_streamlink.sh
recorder_args: []
scanInterval: 300
batchSize: 5
noTerminateOffline: false
streamers: []
