name: PIXIV
plugin: ./plugins/basic
siteUrl: https://sketch.pixiv.net/@
urlback: ""
enable: false
m3u8fetch: scripts/m3u8_streamlink.sh
recorder: scripts/record_streamlink.sh
username: ""
password: ""
scanInterval: 300
batchSize: 5
streamers: []
