name: SMASH
plugin: ./plugins/basic
siteUrl: 'https://www.smashcast.tv/'
urlback: ''
enable: false
m3u8fetch: scripts/m3u8_streamlink.sh
recorder: scripts/record_streamlink.sh
scanInterval: 300
batchSize: 5
streamers: []
