name: TWITCH
plugin: ./lib/plugins/basic
siteUrl: https://www.twitch.tv/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_youtubedl.sh
m3u8fetch_args: []
recorder: scripts/record_ffmpeg.sh
recorder_args: []
scanInterval: 300
batchSize: 5
noTerminateOffline: false
streamers:
  - - peyzki
    - unpaused
