import { Dvr, Config } from "./dvr";
import { Site, Streamer, UpdateCmd } from "./site";
export declare class Tui {
    protected dvr: Dvr;
    protected config: Config;
    protected SITES: Map<string, Site>;
    protected hideOffline: boolean;
    protected listSelect: any;
    protected sitelistSelect: any;
    protected screen: any;
    protected list: any;
    protected sitelist: any;
    protected prompt: any;
    protected inputBar: any;
    protected listmenu: any;
    protected sitemenu: any;
    protected logbody: any;
    constructor(dvr: Dvr);
    protected createTui(): void;
    protected parseCli(tokens: Array<string>): void;
    addSite(site: Site): void;
    redrawSites(): void;
    log(text: string): void;
    protected buildListEntry(site: Site, streamer: Streamer): Array<string>;
    protected populateTable(site: Site, table: Array<Array<string>>): void;
    protected rebuildList(): void;
    render(redrawList: boolean, site?: Site): void;
    protected sleep(time: number): Promise<number>;
    protected updateStreamerList(siteName: string, uid: string, nm: string, cmd: UpdateCmd, isTemp?: boolean, pauseTimer?: number): Promise<void>;
    protected updateSiteList(siteName: string, cmd: UpdateCmd): Promise<void>;
}
